[package]
name = "godot_markdown"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.10.0"
pulldown-cmark-escape = "0.10.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
